#!/bin/bash

class="^Class-Path:.*$"
space="^\s"
colon=".*:.*$"

while read -r line; do

    if [[ $line =~  $class ]]; then
        classPath=$(echo ${line#"Class-Path: "} | tr -d '\n' | tr -d '\r')
        continue
    fi

    if [[ $line =~ $colon ]]; then
      continue
    fi

    if [[ $classPath ]]; then
      classPath="${classPath}$(echo $line | tr -d '\n' | tr -d '\r')"
    fi

done < "$1"

echo $classPath
